# -*- coding: utf-8 -*-
"""
LaTeX writer for Sphinx which allows to use arbitrary LaTeX class.

Also includes clatex_sphinx.py Sphinx extension.
"""

import sys
from os import path
from docutils import nodes
from sphinx import highlighting
import sphinx.writers.latex
import clatex_sphinx
from sphinx.util.osutil import ustrftime
from sphinx.ext.mathbase import latex_visit_math, latex_visit_displaymath, latex_visit_eqref

sphinx.writers.latex.HEADER = r'''%%%% File generated by Sphinx clatex builder
%(documentclass)s

%%%% Added by Sphinx:
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[sc]{mathpazo}
\usepackage{sphinx}
\usepackage{amsthm}
\usepackage{amsmath,amssymb,amstext}
\usepackage{amsfonts}
\usepackage{hyperref}
\usepackage{hypcap}
%(longtable)s
%(tabulary)s
%(multirow)s
%(makeidx)s
\usepackage[margin=2.5cm]{geometry}

\renewcommand*{\familydefault}{\sfdefault}

\newtheorem{definition}{Definition}
\newtheorem{exercise}{Exercise}
\newtheorem{example}{Example}

\DeclareUnicodeCharacter{00A0}{~}

\setcounter{MaxMatrixCols}{20}

%%%% Sphinx: addition's end.

%(preamble)s
'''
HEADER = sphinx.writers.latex.HEADER

sphinx.writers.latex.BEGIN_DOC = \
r'''
\begin{document}
%(begin_doc)s
''' # This goes just after the \begin{document}
BEGIN_DOC = sphinx.writers.latex.BEGIN_DOC

sphinx.writers.latex.FOOTER = \
r'''
%(end_doc)s
\end{document}
'''
FOOTER = sphinx.writers.latex.FOOTER

class CustomLaTeXWriter(sphinx.writers.latex.LaTeXWriter):

    def translate(self):
        visitor = CustomLaTeXTranslator(self.document, self.builder)
        self.document.walkabout(visitor)
        self.output = visitor.astext()

class CustomLaTeXTranslator(sphinx.writers.latex.LaTeXTranslator, nodes.NodeVisitor, object):

    default_elements = {
        'preamble':        '',
        'begin_doc':       '',
        'end_doc':         '',
        'longtable':       '',
        'tabulary':        '\\usepackage{tabulary}',
        'multirow':        '\\usepackage{multirow}',
        'hyperref_args':   '',
        'makeidx':         '',
        'documentclass':   '\documentclass[a4paper,11pt]{book}',
        'papersize':       'a4paper',
        'pointsize':       '11pt',
        'classoptions':    '',
        'extraclassoptions': '',
        'inputenc':        '\\usepackage[utf8]{inputenc}',
        'utf8extra':       '\\DeclareUnicodeCharacter{00A0}{\\nobreakspace}',
        'cmappkg':         '\\usepackage{cmap}',
        'fontenc':         '\\usepackage[T1]{fontenc}',
        'babel':           '\\usepackage{babel}',
        'fontpkg':         '\\usepackage{times}',
        'fncychap':        '\\usepackage[Bjarne]{fncychap}',
        'longtable':       '\\usepackage{longtable}',
        'usepackages':     '',
        'title':           '',
        'date':            '',
        'release':         '',
        'author':          '',
        'logo':            '',
        'releasename':     'Release',
        'makeindex':       '\\makeindex',
        'shorthandoff':    '',
        'maketitle':       '\\maketitle',
        'tableofcontents': '\\tableofcontents',
        'footer':          '',
        'printindex':      '\\printindex',
        'transition':      '\n\n\\bigskip\\hrule{}\\bigskip\n\n',
        'figure_align':    'htbp',
        }

    # todo: I should find a real solution
    def visit_transition(self, node):
        try:
            self.body.append(self.elements['transition'])
        except Exception, e:
            print('ERROR: %s' % e)

    def __init__(self, document, builder):

        # super(type(self), self).__init__(document, builder)
        #nodes.NodeVisitor.__init__(self, document)
        sphinx.writers.latex.LaTeXTranslator.__init__(self, document, builder)
        self.builder = builder
        self.body = []
        self.elements = self.default_elements.copy()
        if type(builder.config.clatex_makeidx) == bool:
            if builder.config.clatex_makeidx:
                makeidx = '\usepackage{makeidx}\n\makeindex'
            else:
                makeidx = ''
        else:
            makeidx = builder.config.clatex_makeidx
        self.elements.update({
            'author':       document.settings.author,
            'title':        document.settings.title,
            'documentclass': builder.config.clatex_documentclass,
            'preamble':     builder.config.clatex_preamble,
            'begin_doc':    builder.config.clatex_begin_doc,
            'end_doc':      builder.config.clatex_end_doc,
            'hyperref_args': builder.config.clatex_hyperref_args,
            'makeidx':      makeidx,
            })
        self.highlighter = highlighting.PygmentsBridge('latex',
            builder.config.pygments_style, builder.config.trim_doctest_flags)
        self.context = []
        self.descstack = []
        self.bibitems = []
        self.table = None
        self.next_table_colspec = None
        # stack of [language, linenothreshold] settings per file
        # the first item here is the default and must not be changed
        # the second item is the default for the master file and can be changed
        # by .. highlight:: directive in the master file
        self.hlsettingstack = 2 * [[builder.config.highlight_language,
                                    sys.maxint]]
        self.footnotestack = []
        self.curfilestack = []
        self.handled_abbrs = set()
        if builder.config.latex_use_parts:
            self.top_sectionlevel = 0
        else:
            if builder.config.clatex_use_chapters:
                self.top_sectionlevel = 1
            else:
                self.top_sectionlevel = 2
        self.next_section_ids = set()
        self.next_figure_ids = set()
        self.next_table_ids = set()
        # flags
        self.verbatim = None
        self.in_title = 0
        self.in_production_list = 0
        self.in_footnote = 0
        self.in_caption = 0
        self.first_document = 1
        self.this_is_the_title = 1
        self.literal_whitespace = 0
        self.no_contractions = 0
        self.compact_list = 0
        self.first_param = 0
        self.previous_spanning_row = 0
        self.previous_spanning_column = 0
        self.remember_multirow = {}
        self.footnote_restricted = False
        self.in_parsed_literal = False
        self.in_term = False
        self.next_hyperlink_ids={}
        self.in_minipage = 0
        self.in_container_literal_block = 0

    def astext(self):
        if self.builder.config.clatex_highlighter:
            return(HEADER % self.elements +
                    self.highlighter.get_stylesheet() +
                    u''.join(self.body) +
                    FOOTER % self.elements)
        else:
            return(HEADER % self.elements +
                    u''.join(self.body) +
                    FOOTER % self.elements)

    def visit_environment(self, node):
        clatex_sphinx.visit_environment_latex(self, node)
    def depart_environment(self, node):
        clatex_sphinx.depart_environment_latex(self, node)

    def visit_textcolor(self, node):
        clatex_sphinx.visit_textcolor_latex(self, node)
    def depart_textcolor(self, node):
        clatex_sphinx.depart_textcolor_latex(self, node)

    def visit_endpar(self, node):
        clatex_sphinx.visit_endpar_latex(self, node)
    def depart_endpar(self, node):
        clatex_sphinx.depart_endpar_latex(self, node)

    def visit_math(self, node):
        latex_visit_math(self, node)
    def depart_math(self, node):
        pass

    def visit_displaymath(self, node):
        latex_visit_displaymath(self, node)
    def depart_displaymath(self, node):
        pass

    def visit_eqref(self, node):
        latex_visit_eqref(self, node)
    def depart_eqref(self, node):
        pass

    def visit_align(self, node):
        clatex_sphinx.visit_align_latex(self, node)
    def depart_align(self, node):
        clatex_sphinx.depart_align_latex(self, node)

    def visit_ifhtml(self, node):
        pass
    def depart_ifhtml(self, node):
        pass

    def visit_iflatex(self, node):
        pass
    def depart_iflatex(self, node):
        pass
